version: '3'

services:
  nginx:
    build: nginx
    ports:
      - 80:80
    networks:
      - node-network
    depends_on:
      - app

  app:
    build: node
    entrypoint: wait-for mysql:3306 -t 40 -- ./start.sh
    ports:
      - 3000:3000
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge